
services:
#################################################
  kos:
    image: simulator
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kos
    command: /home/user/kos/cross-build.sh --target sim --mode online --simulator-ip 172.28.0.2 --server-ip 172.28.0.4 --mqtt-ip 172.28.0.5
    working_dir: /home/user/kos
    user: user
    depends_on:
      - arducopter
      - mqtt-server
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.1
#################################################
  arducopter:
    image: simulator
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: arducopter
    command: /home/user/ardupilot/sitl/arducopter -S --model + --speedup 1 --slave 0  --serial5=tcp:5765:wait --serial6=tcp:5766:wait --serial7=tcp:5767:wait --defaults copter.parm --sim-address=172.28.0.2 --home=60.0144850,27.8200870,20.00,200 -I0
    working_dir: /home/user/ardupilot
    user: user
    restart: always
    ports:
      - "5501:5501"
      - "5502:5502"
      - "5760:5760"
      - "5761:5661"
      - "5762:5762"
      - "5763:5763"
      - "5764:5764"
      - "5765:5765"
      - "5766:5766"
      - "5767:5767"
      - "9005:9005"
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.2
#################################################
  mavproxy:
    image: simulator
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mavproxy
    command: mavproxy.py --out 172.28.5.254:14550 --out 172.28.5.254:14551 --master tcp:172.28.0.2:5760 --sitl 172.28.0.2:5501 --logfile /home/user/mav.tlog --daemon
    working_dir: /home/user/mavproxy
    user: user
    depends_on:
      - arducopter
    restart: always
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.3
#################################################
  orvd:
    image: orvd
    build:
      context: .
      dockerfile: ./orvd.Dockerfile
    container_name: orvd
    working_dir: /home/user/orvd
    restart: always
    environment:
      MQTT_HOST: "172.28.0.5"
    depends_on:
      - mqtt-server
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.4
    ports:
      - "8080:8080"
#################################################
  mqtt-server:
    image: mqtt-server
    build:
      context: .
      dockerfile: ./mqtt-server.Dockerfile
    container_name: mqtt-server
    restart: always
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.5
    ports:
      - "1883:1883"
      - "8883:8883"
#################################################
networks:
  cyberimmune:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
