/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/hobbywing/esc/20013.GetEscID.uavcan
 */

#ifndef COM_HOBBYWING_ESC_GETESCID_HPP_INCLUDED
#define COM_HOBBYWING_ESC_GETESCID_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
# signature from original file location
OVERRIDE_SIGNATURE 0x4E2D

uint8[<=3] payload
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.hobbywing.esc.GetEscID
saturated uint8[<=3] payload
******************************************************************************/

#undef payload

namespace com
{
namespace hobbywing
{
namespace esc
{

template <int _tmpl>
struct UAVCAN_EXPORT GetEscID_
{
    typedef const GetEscID_<_tmpl>& ParameterType;
    typedef GetEscID_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Array< ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 3 > payload;
    };

    enum
    {
        MinBitLen
            = FieldTypes::payload::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::payload::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::payload >::Type payload;

    GetEscID_()
        : payload()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<26 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20013 };

    static const char* getDataTypeFullName()
    {
        return "com.hobbywing.esc.GetEscID";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool GetEscID_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        payload == rhs.payload;
}

template <int _tmpl>
bool GetEscID_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(payload, rhs.payload);
}

template <int _tmpl>
int GetEscID_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::payload::encode(self.payload, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GetEscID_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::payload::decode(self.payload, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature GetEscID_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x00004E2DULL);

    FieldTypes::payload::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef GetEscID_<0> GetEscID;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::hobbywing::esc::GetEscID > _uavcan_gdtr_registrator_GetEscID;

}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::GetEscID >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::GetEscID::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::GetEscID >::stream(Stream& s, ::com::hobbywing::esc::GetEscID::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "payload: ";
    YamlStreamer< ::com::hobbywing::esc::GetEscID::FieldTypes::payload >::stream(s, obj.payload, level + 1);
}

}

namespace com
{
namespace hobbywing
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::GetEscID::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::GetEscID >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

#endif // COM_HOBBYWING_ESC_GETESCID_HPP_INCLUDED