/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/hobbywing/esc/213.SetDirection.uavcan
 */

#ifndef COM_HOBBYWING_ESC_SETDIRECTION_HPP_INCLUDED
#define COM_HOBBYWING_ESC_SETDIRECTION_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
OVERRIDE_SIGNATURE 0x9d793111d262ba68

uint8 DIRECTION_CLOCKWISE = 0
uint8 DIRECTION_COUNTER_CLOCKWISE = 1
uint8 DIRECTION_QUERY = 255
uint8 direction

---
uint8 direction
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.hobbywing.esc.SetDirection
saturated uint8 direction
---
saturated uint8 direction
******************************************************************************/

#undef direction
#undef DIRECTION_CLOCKWISE
#undef DIRECTION_COUNTER_CLOCKWISE
#undef DIRECTION_QUERY
#undef direction

namespace com
{
namespace hobbywing
{
namespace esc
{

struct UAVCAN_EXPORT SetDirection_
{
    template <int _tmpl>
    struct Request_
    {
        typedef const Request_<_tmpl>& ParameterType;
        typedef Request_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > DIRECTION_CLOCKWISE;
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > DIRECTION_COUNTER_CLOCKWISE;
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > DIRECTION_QUERY;
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > direction;
        };

        enum
        {
            MinBitLen
                = FieldTypes::direction::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::direction::MaxBitLen
        };

        // Constants
        static const typename ::uavcan::StorageType< typename ConstantTypes::DIRECTION_CLOCKWISE >::Type DIRECTION_CLOCKWISE; // 0
        static const typename ::uavcan::StorageType< typename ConstantTypes::DIRECTION_COUNTER_CLOCKWISE >::Type DIRECTION_COUNTER_CLOCKWISE; // 1
        static const typename ::uavcan::StorageType< typename ConstantTypes::DIRECTION_QUERY >::Type DIRECTION_QUERY; // 255

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::direction >::Type direction;

        Request_()
            : direction()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<8 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    template <int _tmpl>
    struct Response_
    {
        typedef const Response_<_tmpl>& ParameterType;
        typedef Response_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > direction;
        };

        enum
        {
            MinBitLen
                = FieldTypes::direction::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::direction::MaxBitLen
        };

        // Constants

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::direction >::Type direction;

        Response_()
            : direction()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<8 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    typedef Request_<0> Request;
    typedef Response_<0> Response;

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindService };
    enum { DefaultDataTypeID = 213 };

    static const char* getDataTypeFullName()
    {
        return "com.hobbywing.esc.SetDirection";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

private:
    SetDirection_(); // Don't create objects of this type. Use Request/Response instead.
};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool SetDirection_::Request_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        direction == rhs.direction;
}

template <int _tmpl>
bool SetDirection_::Request_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(direction, rhs.direction);
}

template <int _tmpl>
int SetDirection_::Request_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::direction::encode(self.direction, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int SetDirection_::Request_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::direction::decode(self.direction, codec,  tao_mode);
    return res;
}

template <int _tmpl>
bool SetDirection_::Response_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        direction == rhs.direction;
}

template <int _tmpl>
bool SetDirection_::Response_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(direction, rhs.direction);
}

template <int _tmpl>
int SetDirection_::Response_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::direction::encode(self.direction, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int SetDirection_::Response_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::direction::decode(self.direction, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
inline ::uavcan::DataTypeSignature SetDirection_::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x9D793111D262BA68ULL);

    Request::FieldTypes::direction::extendDataTypeSignature(signature);

    Response::FieldTypes::direction::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename SetDirection_::Request_<_tmpl>::ConstantTypes::DIRECTION_CLOCKWISE >::Type
    SetDirection_::Request_<_tmpl>::DIRECTION_CLOCKWISE = 0U; // 0

template <int _tmpl>
const typename ::uavcan::StorageType< typename SetDirection_::Request_<_tmpl>::ConstantTypes::DIRECTION_COUNTER_CLOCKWISE >::Type
    SetDirection_::Request_<_tmpl>::DIRECTION_COUNTER_CLOCKWISE = 1U; // 1

template <int _tmpl>
const typename ::uavcan::StorageType< typename SetDirection_::Request_<_tmpl>::ConstantTypes::DIRECTION_QUERY >::Type
    SetDirection_::Request_<_tmpl>::DIRECTION_QUERY = 255U; // 255

/*
 * Final typedef
 */
typedef SetDirection_ SetDirection;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::hobbywing::esc::SetDirection > _uavcan_gdtr_registrator_SetDirection;

}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::SetDirection::Request >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::SetDirection::Request::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::SetDirection::Request >::stream(Stream& s, ::com::hobbywing::esc::SetDirection::Request::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "direction: ";
    YamlStreamer< ::com::hobbywing::esc::SetDirection::Request::FieldTypes::direction >::stream(s, obj.direction, level + 1);
}

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::SetDirection::Response >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::SetDirection::Response::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::SetDirection::Response >::stream(Stream& s, ::com::hobbywing::esc::SetDirection::Response::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "direction: ";
    YamlStreamer< ::com::hobbywing::esc::SetDirection::Response::FieldTypes::direction >::stream(s, obj.direction, level + 1);
}

}

namespace com
{
namespace hobbywing
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::SetDirection::Request::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::SetDirection::Request >::stream(s, obj, 0);
    return s;
}

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::SetDirection::Response::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::SetDirection::Response >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

#endif // COM_HOBBYWING_ESC_SETDIRECTION_HPP_INCLUDED