from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='front_left_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/front_left_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='front_right_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/front_right_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='mid_left_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/mid_left_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='mid_right_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/mid_right_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='rear_left_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/rear_left_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='rear_right_wheel_bridge',
            arguments=[
                '/model/wildthumper/joint/rear_right_wheel_joint/cmd_vel@std_msgs/msg/Float64@gz.msgs.Double'
            ],
            output='screen'
        ),
        Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name='imu_bridge',
            arguments=[
                '/model/wildthumper/imu_sensor/imu@sensor_msgs/msg/Imu@gz.msgs.IMU'
            ],
            output='screen'
        ),
    ])