/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/tmotor/esc/1039.PUSHCAN.uavcan
 */

#ifndef COM_TMOTOR_ESC_PUSHCAN_HPP_INCLUDED
#define COM_TMOTOR_ESC_PUSHCAN_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Generic ESC status.
#

OVERRIDE_SIGNATURE 0xAACF9B4B2577BC6E

uint32 data_sequence  #data sequence

uint8[<=255] data
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.tmotor.esc.PUSHCAN
saturated uint32 data_sequence
saturated uint8[<=255] data
******************************************************************************/

#undef data_sequence
#undef data

namespace com
{
namespace tmotor
{
namespace esc
{

template <int _tmpl>
struct UAVCAN_EXPORT PUSHCAN_
{
    typedef const PUSHCAN_<_tmpl>& ParameterType;
    typedef PUSHCAN_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 32, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > data_sequence;
        typedef ::uavcan::Array< ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 255 > data;
    };

    enum
    {
        MinBitLen
            = FieldTypes::data_sequence::MinBitLen
            + FieldTypes::data::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::data_sequence::MaxBitLen
            + FieldTypes::data::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::data_sequence >::Type data_sequence;
    typename ::uavcan::StorageType< typename FieldTypes::data >::Type data;

    PUSHCAN_()
        : data_sequence()
        , data()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<2080 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 1039 };

    static const char* getDataTypeFullName()
    {
        return "com.tmotor.esc.PUSHCAN";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool PUSHCAN_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        data_sequence == rhs.data_sequence &&
        data == rhs.data;
}

template <int _tmpl>
bool PUSHCAN_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(data_sequence, rhs.data_sequence) &&
        ::uavcan::areClose(data, rhs.data);
}

template <int _tmpl>
int PUSHCAN_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::data_sequence::encode(self.data_sequence, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::data::encode(self.data, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int PUSHCAN_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::data_sequence::decode(self.data_sequence, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::data::decode(self.data, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature PUSHCAN_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xAACF9B4B2577BC6EULL);

    FieldTypes::data_sequence::extendDataTypeSignature(signature);
    FieldTypes::data::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef PUSHCAN_<0> PUSHCAN;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::tmotor::esc::PUSHCAN > _uavcan_gdtr_registrator_PUSHCAN;

}

} // Namespace esc
} // Namespace tmotor
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::tmotor::esc::PUSHCAN >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::tmotor::esc::PUSHCAN::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::tmotor::esc::PUSHCAN >::stream(Stream& s, ::com::tmotor::esc::PUSHCAN::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "data_sequence: ";
    YamlStreamer< ::com::tmotor::esc::PUSHCAN::FieldTypes::data_sequence >::stream(s, obj.data_sequence, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "data: ";
    YamlStreamer< ::com::tmotor::esc::PUSHCAN::FieldTypes::data >::stream(s, obj.data, level + 1);
}

}

namespace com
{
namespace tmotor
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::tmotor::esc::PUSHCAN::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::tmotor::esc::PUSHCAN >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace tmotor
} // Namespace com

#endif // COM_TMOTOR_ESC_PUSHCAN_HPP_INCLUDED