/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/xacti/20306.GnssStatusReq.uavcan
 */

#ifndef COM_XACTI_GNSSSTATUSREQ_HPP_INCLUDED
#define COM_XACTI_GNSSSTATUSREQ_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Xacti GNSS status request
#

# signature from original file location
OVERRIDE_SIGNATURE 0x60F5464E1CA03449

#
# requirement
# 0: clear buffer command
# 1 ~ 21: request sequence
#
uint8 requirement
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.xacti.GnssStatusReq
saturated uint8 requirement
******************************************************************************/

#undef requirement

namespace com
{
namespace xacti
{

template <int _tmpl>
struct UAVCAN_EXPORT GnssStatusReq_
{
    typedef const GnssStatusReq_<_tmpl>& ParameterType;
    typedef GnssStatusReq_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > requirement;
    };

    enum
    {
        MinBitLen
            = FieldTypes::requirement::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::requirement::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::requirement >::Type requirement;

    GnssStatusReq_()
        : requirement()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<8 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20306 };

    static const char* getDataTypeFullName()
    {
        return "com.xacti.GnssStatusReq";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool GnssStatusReq_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        requirement == rhs.requirement;
}

template <int _tmpl>
bool GnssStatusReq_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(requirement, rhs.requirement);
}

template <int _tmpl>
int GnssStatusReq_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::requirement::encode(self.requirement, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GnssStatusReq_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::requirement::decode(self.requirement, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature GnssStatusReq_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x60F5464E1CA03449ULL);

    FieldTypes::requirement::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef GnssStatusReq_<0> GnssStatusReq;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::xacti::GnssStatusReq > _uavcan_gdtr_registrator_GnssStatusReq;

}

} // Namespace xacti
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::xacti::GnssStatusReq >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::xacti::GnssStatusReq::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::xacti::GnssStatusReq >::stream(Stream& s, ::com::xacti::GnssStatusReq::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "requirement: ";
    YamlStreamer< ::com::xacti::GnssStatusReq::FieldTypes::requirement >::stream(s, obj.requirement, level + 1);
}

}

namespace com
{
namespace xacti
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::xacti::GnssStatusReq::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::xacti::GnssStatusReq >::stream(s, obj, 0);
    return s;
}

} // Namespace xacti
} // Namespace com

#endif // COM_XACTI_GNSSSTATUSREQ_HPP_INCLUDED