package drone_controller.AutopilotConnectorInterface

const UInt16 MaxMissionLength = 1024;

interface {
    WaitForArmRequest(out UInt8 success);
    PermitArm(out UInt8 success);
    ForbidArm(out UInt8 success);
    PauseFlight(out UInt8 success);
    ResumeFlight(out UInt8 success);
    AbortMission(out UInt8 success);
    ChangeSpeed(in SInt32 speed, out UInt8 success);
    ChangeAltitude(in SInt32 altitude, out UInt8 success);
    ChangeWaypoint(in SInt32 latitude, in SInt32 longitude, in SInt32 altitude, out UInt8 success);
    SetMission(in sequence<UInt8, MaxMissionLength> mission, in UInt32 size, out UInt8 success);
}