package drone_controller.CredentialManagerInterface

const UInt16 MaxMessageLength = 4096;
const UInt16 MaxSignatureLength = 257;

interface {
    SignMessage(in string<MaxMessageLength> message, out UInt8 success, out string<MaxSignatureLength> signature);
    CheckSignature(in string<MaxMessageLength> message, out UInt8 success, out UInt8 correct);
}