package drone_controller.CredentialManagerInterface

const UInt16 MaxKeyLength = 257;
const UInt16 MaxRawKeyLength = 1024;
const UInt16 MaxMessageLength = 1024;
const UInt16 MaxSignatureLength = 257;

interface {
    GetRsaKey(out UInt8 success, out string<MaxKeyLength> e, out string<MaxKeyLength> n);
    SetRsaKey(in string<MaxRawKeyLength> key, out UInt8 success);
    SignMessage(in string<MaxMessageLength> message, out UInt8 success, out string<MaxSignatureLength> signature);
    CheckSignature(in string<MaxMessageLength> message, out UInt8 success, out UInt8 correct);
}