package drone_controller.ServerConnectorInterface

const UInt16 MaxIdLength = 32;
const UInt16 MaxQueryLength = 1024;
const UInt16 MaxResponseLength = 4096;
const UInt16 MaxTopicLength = 64;
const UInt16 MaxPublicationLength = 1024;

interface {
    GetBoardId(out UInt8 success, out string<MaxIdLength> id);
    SendRequest(in string<MaxQueryLength> query, out UInt8 success, out string<MaxResponseLength> response);
    PublishMessage(in string<MaxTopicLength> topic, in string<MaxPublicationLength> publication, out UInt8 success);
}