/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/hobbywing/esc/241.GetMaintenanceInformation.uavcan
 */

#ifndef COM_HOBBYWING_ESC_GETMAINTENANCEINFORMATION_HPP_INCLUDED
#define COM_HOBBYWING_ESC_GETMAINTENANCEINFORMATION_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
OVERRIDE_SIGNATURE 0xb81dbd4ec9a5977d

uint8 OPTION_CLEAR = 1
uint8 option

---

uint32 total_rotation_time_min
uint24 time_since_maintainence_min
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.hobbywing.esc.GetMaintenanceInformation
saturated uint8 option
---
saturated uint32 total_rotation_time_min
saturated uint24 time_since_maintainence_min
******************************************************************************/

#undef option
#undef OPTION_CLEAR
#undef total_rotation_time_min
#undef time_since_maintainence_min

namespace com
{
namespace hobbywing
{
namespace esc
{

struct UAVCAN_EXPORT GetMaintenanceInformation_
{
    template <int _tmpl>
    struct Request_
    {
        typedef const Request_<_tmpl>& ParameterType;
        typedef Request_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > OPTION_CLEAR;
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > option;
        };

        enum
        {
            MinBitLen
                = FieldTypes::option::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::option::MaxBitLen
        };

        // Constants
        static const typename ::uavcan::StorageType< typename ConstantTypes::OPTION_CLEAR >::Type OPTION_CLEAR; // 1

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::option >::Type option;

        Request_()
            : option()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<8 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    template <int _tmpl>
    struct Response_
    {
        typedef const Response_<_tmpl>& ParameterType;
        typedef Response_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 32, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > total_rotation_time_min;
            typedef ::uavcan::IntegerSpec< 24, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > time_since_maintainence_min;
        };

        enum
        {
            MinBitLen
                = FieldTypes::total_rotation_time_min::MinBitLen
                + FieldTypes::time_since_maintainence_min::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::total_rotation_time_min::MaxBitLen
                + FieldTypes::time_since_maintainence_min::MaxBitLen
        };

        // Constants

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::total_rotation_time_min >::Type total_rotation_time_min;
        typename ::uavcan::StorageType< typename FieldTypes::time_since_maintainence_min >::Type time_since_maintainence_min;

        Response_()
            : total_rotation_time_min()
            , time_since_maintainence_min()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<56 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    typedef Request_<0> Request;
    typedef Response_<0> Response;

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindService };
    enum { DefaultDataTypeID = 241 };

    static const char* getDataTypeFullName()
    {
        return "com.hobbywing.esc.GetMaintenanceInformation";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

private:
    GetMaintenanceInformation_(); // Don't create objects of this type. Use Request/Response instead.
};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool GetMaintenanceInformation_::Request_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        option == rhs.option;
}

template <int _tmpl>
bool GetMaintenanceInformation_::Request_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(option, rhs.option);
}

template <int _tmpl>
int GetMaintenanceInformation_::Request_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::option::encode(self.option, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GetMaintenanceInformation_::Request_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::option::decode(self.option, codec,  tao_mode);
    return res;
}

template <int _tmpl>
bool GetMaintenanceInformation_::Response_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        total_rotation_time_min == rhs.total_rotation_time_min &&
        time_since_maintainence_min == rhs.time_since_maintainence_min;
}

template <int _tmpl>
bool GetMaintenanceInformation_::Response_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(total_rotation_time_min, rhs.total_rotation_time_min) &&
        ::uavcan::areClose(time_since_maintainence_min, rhs.time_since_maintainence_min);
}

template <int _tmpl>
int GetMaintenanceInformation_::Response_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::total_rotation_time_min::encode(self.total_rotation_time_min, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::time_since_maintainence_min::encode(self.time_since_maintainence_min, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GetMaintenanceInformation_::Response_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::total_rotation_time_min::decode(self.total_rotation_time_min, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::time_since_maintainence_min::decode(self.time_since_maintainence_min, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
inline ::uavcan::DataTypeSignature GetMaintenanceInformation_::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xB81DBD4EC9A5977DULL);

    Request::FieldTypes::option::extendDataTypeSignature(signature);

    Response::FieldTypes::total_rotation_time_min::extendDataTypeSignature(signature);
    Response::FieldTypes::time_since_maintainence_min::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename GetMaintenanceInformation_::Request_<_tmpl>::ConstantTypes::OPTION_CLEAR >::Type
    GetMaintenanceInformation_::Request_<_tmpl>::OPTION_CLEAR = 1U; // 1

/*
 * Final typedef
 */
typedef GetMaintenanceInformation_ GetMaintenanceInformation;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::hobbywing::esc::GetMaintenanceInformation > _uavcan_gdtr_registrator_GetMaintenanceInformation;

}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Request >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Request::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Request >::stream(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Request::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "option: ";
    YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Request::FieldTypes::option >::stream(s, obj.option, level + 1);
}

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Response >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Response::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Response >::stream(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Response::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "total_rotation_time_min: ";
    YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Response::FieldTypes::total_rotation_time_min >::stream(s, obj.total_rotation_time_min, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "time_since_maintainence_min: ";
    YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Response::FieldTypes::time_since_maintainence_min >::stream(s, obj.time_since_maintainence_min, level + 1);
}

}

namespace com
{
namespace hobbywing
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Request::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Request >::stream(s, obj, 0);
    return s;
}

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::GetMaintenanceInformation::Response::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::GetMaintenanceInformation::Response >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

#endif // COM_HOBBYWING_ESC_GETMAINTENANCEINFORMATION_HPP_INCLUDED