/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/hobbywing/esc/20100.RawCommand.uavcan
 */

#ifndef COM_HOBBYWING_ESC_RAWCOMMAND_HPP_INCLUDED
#define COM_HOBBYWING_ESC_RAWCOMMAND_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
OVERRIDE_SIGNATURE 0xbdf086c79f6640ad

int14[<=8] command
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.hobbywing.esc.RawCommand
saturated int14[<=8] command
******************************************************************************/

#undef command

namespace com
{
namespace hobbywing
{
namespace esc
{

template <int _tmpl>
struct UAVCAN_EXPORT RawCommand_
{
    typedef const RawCommand_<_tmpl>& ParameterType;
    typedef RawCommand_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Array< ::uavcan::IntegerSpec< 14, ::uavcan::SignednessSigned, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 8 > command;
    };

    enum
    {
        MinBitLen
            = FieldTypes::command::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::command::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::command >::Type command;

    RawCommand_()
        : command()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<116 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20100 };

    static const char* getDataTypeFullName()
    {
        return "com.hobbywing.esc.RawCommand";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool RawCommand_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        command == rhs.command;
}

template <int _tmpl>
bool RawCommand_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(command, rhs.command);
}

template <int _tmpl>
int RawCommand_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::command::encode(self.command, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int RawCommand_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::command::decode(self.command, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature RawCommand_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xBDF086C79F6640ADULL);

    FieldTypes::command::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef RawCommand_<0> RawCommand;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::hobbywing::esc::RawCommand > _uavcan_gdtr_registrator_RawCommand;

}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::RawCommand >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::RawCommand::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::RawCommand >::stream(Stream& s, ::com::hobbywing::esc::RawCommand::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "command: ";
    YamlStreamer< ::com::hobbywing::esc::RawCommand::FieldTypes::command >::stream(s, obj.command, level + 1);
}

}

namespace com
{
namespace hobbywing
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::RawCommand::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::RawCommand >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

#endif // COM_HOBBYWING_ESC_RAWCOMMAND_HPP_INCLUDED