/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/user/cyberimmune-systems-autonomous-delivery-drone-with-kos-contest/modules/DroneCAN/DSDL/com/hobbywing/esc/215.SetThrottleSource.uavcan
 */

#ifndef COM_HOBBYWING_ESC_SETTHROTTLESOURCE_HPP_INCLUDED
#define COM_HOBBYWING_ESC_SETTHROTTLESOURCE_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
OVERRIDE_SIGNATURE 0x0c248faaefe5e29a

uint8 SOURCE_CAN_DIGITAL = 0
uint8 SOURCE_PWM = 1
uint8 source

---

uint8 source
******************************************************************************/

/********************* DSDL signature source definition ***********************
com.hobbywing.esc.SetThrottleSource
saturated uint8 source
---
saturated uint8 source
******************************************************************************/

#undef source
#undef SOURCE_CAN_DIGITAL
#undef SOURCE_PWM
#undef source

namespace com
{
namespace hobbywing
{
namespace esc
{

struct UAVCAN_EXPORT SetThrottleSource_
{
    template <int _tmpl>
    struct Request_
    {
        typedef const Request_<_tmpl>& ParameterType;
        typedef Request_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > SOURCE_CAN_DIGITAL;
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > SOURCE_PWM;
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > source;
        };

        enum
        {
            MinBitLen
                = FieldTypes::source::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::source::MaxBitLen
        };

        // Constants
        static const typename ::uavcan::StorageType< typename ConstantTypes::SOURCE_CAN_DIGITAL >::Type SOURCE_CAN_DIGITAL; // 0
        static const typename ::uavcan::StorageType< typename ConstantTypes::SOURCE_PWM >::Type SOURCE_PWM; // 1

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::source >::Type source;

        Request_()
            : source()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<8 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    template <int _tmpl>
    struct Response_
    {
        typedef const Response_<_tmpl>& ParameterType;
        typedef Response_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > source;
        };

        enum
        {
            MinBitLen
                = FieldTypes::source::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::source::MaxBitLen
        };

        // Constants

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::source >::Type source;

        Response_()
            : source()
        {
            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<8 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    };

    typedef Request_<0> Request;
    typedef Response_<0> Response;

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindService };
    enum { DefaultDataTypeID = 215 };

    static const char* getDataTypeFullName()
    {
        return "com.hobbywing.esc.SetThrottleSource";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

private:
    SetThrottleSource_(); // Don't create objects of this type. Use Request/Response instead.
};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool SetThrottleSource_::Request_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        source == rhs.source;
}

template <int _tmpl>
bool SetThrottleSource_::Request_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(source, rhs.source);
}

template <int _tmpl>
int SetThrottleSource_::Request_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::source::encode(self.source, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int SetThrottleSource_::Request_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::source::decode(self.source, codec,  tao_mode);
    return res;
}

template <int _tmpl>
bool SetThrottleSource_::Response_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        source == rhs.source;
}

template <int _tmpl>
bool SetThrottleSource_::Response_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(source, rhs.source);
}

template <int _tmpl>
int SetThrottleSource_::Response_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::source::encode(self.source, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int SetThrottleSource_::Response_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::source::decode(self.source, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
inline ::uavcan::DataTypeSignature SetThrottleSource_::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xC248FAAEFE5E29AULL);

    Request::FieldTypes::source::extendDataTypeSignature(signature);

    Response::FieldTypes::source::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename SetThrottleSource_::Request_<_tmpl>::ConstantTypes::SOURCE_CAN_DIGITAL >::Type
    SetThrottleSource_::Request_<_tmpl>::SOURCE_CAN_DIGITAL = 0U; // 0

template <int _tmpl>
const typename ::uavcan::StorageType< typename SetThrottleSource_::Request_<_tmpl>::ConstantTypes::SOURCE_PWM >::Type
    SetThrottleSource_::Request_<_tmpl>::SOURCE_PWM = 1U; // 1

/*
 * Final typedef
 */
typedef SetThrottleSource_ SetThrottleSource;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::com::hobbywing::esc::SetThrottleSource > _uavcan_gdtr_registrator_SetThrottleSource;

}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Request >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Request::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Request >::stream(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Request::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "source: ";
    YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Request::FieldTypes::source >::stream(s, obj.source, level + 1);
}

template <>
class UAVCAN_EXPORT YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Response >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Response::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Response >::stream(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Response::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "source: ";
    YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Response::FieldTypes::source >::stream(s, obj.source, level + 1);
}

}

namespace com
{
namespace hobbywing
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Request::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Request >::stream(s, obj, 0);
    return s;
}

template <typename Stream>
inline Stream& operator<<(Stream& s, ::com::hobbywing::esc::SetThrottleSource::Response::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::com::hobbywing::esc::SetThrottleSource::Response >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace hobbywing
} // Namespace com

#endif // COM_HOBBYWING_ESC_SETTHROTTLESOURCE_HPP_INCLUDED